module.exports = {
  ENVIRONMENT: ${SERVER_ENVIRONMENT},
  DOMAIN_BASEPATH: ${SERVER_DOMAIN_BASEPATH},
  DB_MARIADB_HOST: ${SERVER_DB_MARIADB_HOST},
  DB_MARIADB_USER: ${SERVER_DB_MARIADB_USER},
  DB_MARIADB_PASSWORD: ${SERVER_DB_MARIADB_PASSWORD},
  DB_MARIADB_DBNAME: ${SERVER_DB_MARIADB_DBNAME},
  DB_MARIADB_PORT: ${SERVER_DB_MARIADB_PORT},
};
